version: "3.8"

services:
  tagline_task:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/tagline_task
    ports:
      - 8000:8000
    image: tagline-task-image
    container_name: tagline-task-container
    command: >
      sh -c   "python manage.py collectstatic &&
              python manage.py migrate &&
              gunicorn -c gunicorn.py"

